name: Simple Minetest Server Build

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
      env:
        LANG: C.UTF-8
        DEBIAN_FRONTEND: noninteractive

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          build-essential cmake ninja-build git \
          libsqlite3-dev libzstd-dev libcurl4-openssl-dev \
          libncurses-dev libgmp-dev \
          libjsoncpp-dev libssl-dev zlib1g-dev \
          ca-certificates wget binutils dpkg-dev \
          gettext pkg-config
        apt-get clean
        rm -rf /var/lib/apt/lists/*

    - name: Build server
      run: chmod +x build.sh && ./build.sh

    - name: Upload to Releases
      uses: softprops/action-gh-release@v1
      with:
        files: minetest/build/minetest-server_5.12.0_bookworm_amd64.deb
        tag_name: latest-build
        name: Latest Minetest Server Build
        body: Continuous build from main branch
        prerelease: true
        overwrite: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
