name: Build Minetest Server 5.12 DEB

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-minetest-server:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
      env:
        LANG: C.UTF-8
        DEBIAN_FRONTEND: noninteractive

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          build-essential cmake ninja-build git \
          libsqlite3-dev libzstd-dev libcurl4-openssl-dev \
          libncurses-dev libgmp-dev \
          libjsoncpp-dev libssl-dev zlib1g-dev \
          ca-certificates wget binutils dpkg-dev \
          gettext pkg-config
        
        # Clean up
        apt-get clean
        rm -rf /var/lib/apt/lists/*

    - name: Build Minetest Server
      run: chmod +x build.sh && ./build.sh

    - name: Upload Minetest Server DEB
      uses: actions/upload-artifact@v4
      with:
        name: minetest-server-deb
        path: minetest/build/minetest-server_5.12.0_bookworm_amd64.deb
