name: Simple Minetest Server Build

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
      env:
        LANG: C.UTF-8
        DEBIAN_FRONTEND: noninteractive

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          build-essential cmake ninja-build git \
          libsqlite3-dev libzstd-dev libcurl4-openssl-dev \
          libncurses-dev libgmp-dev \
          libjsoncpp-dev libssl-dev zlib1g-dev \
          ca-certificates wget binutils dpkg-dev \
          gettext pkg-config
        apt-get clean
        rm -rf /var/lib/apt/lists/*

    - name: Build server
      run: chmod +x build.sh && ./build.sh

    - name: Setup Release
      id: create_release
      uses: actions/create-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest-build
        release_name: Latest Minetest Server Build
        draft: false
        prerelease: true
        body: "Continuous build from main branch"
        overwrite: true

    - name: Upload Package
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: minetest/build/minetest-server_5.12.0_bookworm_amd64.deb
        asset_name: minetest-server.deb
        asset_content_type: application/vnd.debian.binary-package
