name: build

on: [push, pull_request]

jobs:
  linux-server-build:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
      env: { LANG: "C.UTF-8" }
    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          apt-get update
          apt-get install -y \
            g++ make ninja-build libc6-dev cmake \
            libsqlite3-dev \
            libcurl4-openssl-dev \
            zlib1g-dev libgmp-dev \
            libleveldb-dev gettext \
            ca-certificates wget file libncurses-dev \
            binutils dpkg-dev  # Nuevas dependencias para empaquetado .deb
          
          wget https://github.com/principia-game/linux-deps/releases/download/latest/deps.tar.gz -O linux-deps.tar.gz
          tar -xaf linux-deps.tar.gz -C /

      - name: Clonar repositorio Luanti
        uses: actions/checkout@v4
        with:
          repository: minetest/minetest
          path: luanti
          ref: 5.12.0

      - name: Clonar repositorio LuaJIT
        uses: actions/checkout@v4
        with:
          repository: LuaJIT/LuaJIT
          path: luajit

      - name: Compilar y empaquetar
        run: chmod +x build.sh && ./build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: server-package
          path: |
            luanti/build/luanti-server_*.deb
            luanti/build/luanti-server.debug
          if-no-files-found: error
