name: Build and Deploy Luanti Server

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
      env:
        LANG: C.UTF-8
        DEBIAN_FRONTEND: noninteractive

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          g++ make libc6-dev cmake libpng-dev libjpeg-dev \
          libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev \
          libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev \
          libgmp-dev libjsoncpp-dev libzstd-dev libluajit-5.1-dev \
          gettext libsdl2-dev git ca-certificates wget binutils dpkg-dev \
          ninja-build pkg-config
        apt-get clean
        rm -rf /var/lib/apt/lists/*

    - name: Build server
      run: |
        git clone --depth 1 https://github.com/luanti-org/luanti
        cd luanti
        cmake . -DRUN_IN_PLACE=FALSE -DBUILD_SERVER=TRUE -DBUILD_CLIENT=FALSE -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
        cpack -G DEB
        mv luanti-*.deb ../luanti-server.deb
        cd ..

    - name: Verify DEB file exists
      run: ls -la luanti-server.deb

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: luanti-server
        path: luanti-server.deb

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: luanti-server
        path: dist

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Rename to latest
      run: mv dist/luanti-server.deb dist/luanti-server-latest.deb

    - name: Upload to Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist

  pages-build-deployment:
    needs: deploy
    permissions:
      pages: write  # Fixed permissions
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
